services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: prn232_sqlserver
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
      MSSQL_SA_PASSWORD: "${MSSQL_SA_PASSWORD}"
      MSSQL_MEMORY_LIMIT_MB: "2048"
    ports:
      - "14333:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
      - ./data:/var/opt/backup

  backend:
    build:
      context: ./src/backend/Api_RestAPI_gradingTool
      dockerfile: Dockerfile
    container_name: prn232_backend
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__Default=Server=sqlserver,1433;Database=PRN232_GradingTool;User Id=sa;Password=${MSSQL_SA_PASSWORD};Encrypt=False;TrustServerCertificate=True;
      - Runner__ExecutablePath=../Runner/Runner.csproj
    depends_on:
      - sqlserver

volumes:
  sqlserver_data:
