/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { SubmissionDtoPagedResult } from '../../models/submission-dto-paged-result';

export interface ApiExamsExamIdSubmissionsGet$Plain$Params {
  examId: number;
  search?: string;
  sort?: string;
  order?: string;
  page?: number;
  pageSize?: number;
}

export function apiExamsExamIdSubmissionsGet$Plain(http: HttpClient, rootUrl: string, params: ApiExamsExamIdSubmissionsGet$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<SubmissionDtoPagedResult>> {
  const rb = new RequestBuilder(rootUrl, apiExamsExamIdSubmissionsGet$Plain.PATH, 'get');
  if (params) {
    rb.path('examId', params.examId, {});
    rb.query('search', params.search, {});
    rb.query('sort', params.sort, {});
    rb.query('order', params.order, {});
    rb.query('page', params.page, {});
    rb.query('pageSize', params.pageSize, {});
  }

  return http.request(
    rb.build({ responseType: 'text', accept: 'text/plain', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<SubmissionDtoPagedResult>;
    })
  );
}

apiExamsExamIdSubmissionsGet$Plain.PATH = '/api/exams/{examId}/submissions';
