/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { SubmissionDto } from '../../models/submission-dto';

export interface ApiSubmissionsIdRegradeRequestsPost$Json$Params {
  id: number;
}

export function apiSubmissionsIdRegradeRequestsPost$Json(http: HttpClient, rootUrl: string, params: ApiSubmissionsIdRegradeRequestsPost$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<SubmissionDto>> {
  const rb = new RequestBuilder(rootUrl, apiSubmissionsIdRegradeRequestsPost$Json.PATH, 'post');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'text/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<SubmissionDto>;
    })
  );
}

apiSubmissionsIdRegradeRequestsPost$Json.PATH = '/api/submissions/{id}/regrade-requests';
