/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { SubmissionDto } from '../../models/submission-dto';

export interface ApiSubmissionsIdRequeuePost$Plain$Params {
  id: number;
}

export function apiSubmissionsIdRequeuePost$Plain(http: HttpClient, rootUrl: string, params: ApiSubmissionsIdRequeuePost$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<SubmissionDto>> {
  const rb = new RequestBuilder(rootUrl, apiSubmissionsIdRequeuePost$Plain.PATH, 'post');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'text', accept: 'text/plain', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<SubmissionDto>;
    })
  );
}

apiSubmissionsIdRequeuePost$Plain.PATH = '/api/submissions/{id}/requeue';
