// <auto-generated />
using System;
using Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(GradingDbContext))]
    [Migration("20260312103743_RemoveEndpointSpec")]
    partial class RemoveEndpointSpec
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Infrastructure.Exam", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CollectionFilePath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<string>("DatabaseFilePath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("SessionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "SessionId" }, "IX_Exams_SessionId");

                    b.ToTable("Exams");
                });

            modelBuilder.Entity("Infrastructure.ExamSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("SemesterId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "SemesterId" }, "IX_ExamSessions_SemesterId");

                    b.ToTable("ExamSessions");
                });

            modelBuilder.Entity("Infrastructure.Semester", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.ToTable("Semesters");
                });

            modelBuilder.Entity("Infrastructure.Submission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ExamId")
                        .HasColumnType("int");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("LastError")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("StudentName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("SubmittedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<decimal>("TotalScore")
                        .HasColumnType("decimal(8, 2)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "ExamId" }, "IX_Submissions_ExamId");

                    b.HasIndex(new[] { "Status" }, "IX_Submissions_Status");

                    b.ToTable("Submissions");
                });

            modelBuilder.Entity("Infrastructure.TestCase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<int?>("DependencyTestCaseId")
                        .HasColumnType("int");

                    b.Property<int>("ExamId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("Score")
                        .HasColumnType("decimal(6, 2)");

                    b.Property<string>("ScriptContent")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "DependencyTestCaseId" }, "IX_TestCases_DependencyTestCaseId");

                    b.HasIndex(new[] { "ExamId" }, "IX_TestCases_ExamId");

                    b.ToTable("TestCases");
                });

            modelBuilder.Entity("Infrastructure.TestResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<decimal>("EarnedScore")
                        .HasColumnType("decimal(8, 2)");

                    b.Property<bool>("IsPassed")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSkipped")
                        .HasColumnType("bit");

                    b.Property<string>("Log")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SubmissionId")
                        .HasColumnType("int");

                    b.Property<int>("TestCaseId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "SubmissionId" }, "IX_TestResults_SubmissionId");

                    b.HasIndex(new[] { "TestCaseId" }, "IX_TestResults_TestCaseId");

                    b.HasIndex(new[] { "SubmissionId", "TestCaseId" }, "UQ_TestResults_Submission_TestCase")
                        .IsUnique();

                    b.ToTable("TestResults");
                });

            modelBuilder.Entity("Infrastructure.Exam", b =>
                {
                    b.HasOne("Infrastructure.ExamSession", "Session")
                        .WithMany("Exams")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Exams_ExamSessions");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("Infrastructure.ExamSession", b =>
                {
                    b.HasOne("Infrastructure.Semester", "Semester")
                        .WithMany("ExamSessions")
                        .HasForeignKey("SemesterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ExamSessions_Semesters");

                    b.Navigation("Semester");
                });

            modelBuilder.Entity("Infrastructure.Submission", b =>
                {
                    b.HasOne("Infrastructure.Exam", "Exam")
                        .WithMany("Submissions")
                        .HasForeignKey("ExamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Submissions_Exams");

                    b.Navigation("Exam");
                });

            modelBuilder.Entity("Infrastructure.TestCase", b =>
                {
                    b.HasOne("Infrastructure.TestCase", "DependencyTestCase")
                        .WithMany("InverseDependencyTestCase")
                        .HasForeignKey("DependencyTestCaseId")
                        .HasConstraintName("FK_TestCases_Dependency");

                    b.HasOne("Infrastructure.Exam", "Exam")
                        .WithMany("TestCases")
                        .HasForeignKey("ExamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_TestCases_Exams");

                    b.Navigation("DependencyTestCase");

                    b.Navigation("Exam");
                });

            modelBuilder.Entity("Infrastructure.TestResult", b =>
                {
                    b.HasOne("Infrastructure.Submission", "Submission")
                        .WithMany("TestResults")
                        .HasForeignKey("SubmissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_TestResults_Submissions");

                    b.HasOne("Infrastructure.TestCase", "TestCase")
                        .WithMany("TestResults")
                        .HasForeignKey("TestCaseId")
                        .IsRequired()
                        .HasConstraintName("FK_TestResults_TestCases");

                    b.Navigation("Submission");

                    b.Navigation("TestCase");
                });

            modelBuilder.Entity("Infrastructure.Exam", b =>
                {
                    b.Navigation("Submissions");

                    b.Navigation("TestCases");
                });

            modelBuilder.Entity("Infrastructure.ExamSession", b =>
                {
                    b.Navigation("Exams");
                });

            modelBuilder.Entity("Infrastructure.Semester", b =>
                {
                    b.Navigation("ExamSessions");
                });

            modelBuilder.Entity("Infrastructure.Submission", b =>
                {
                    b.Navigation("TestResults");
                });

            modelBuilder.Entity("Infrastructure.TestCase", b =>
                {
                    b.Navigation("InverseDependencyTestCase");

                    b.Navigation("TestResults");
                });
#pragma warning restore 612, 618
        }
    }
}
