// <auto-generated />
using System;
using Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(GradingDbContext))]
    [Migration("20260319093843_AddExamConfigOverrides")]
    partial class AddExamConfigOverrides
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Infrastructure.Exam", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CollectionFilePath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<string>("DatabaseFilePath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("EndpointSpecFilePath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("EnvironmentFilePath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("HealthPath")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NewmanExtraArgs")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("SessionId")
                        .HasColumnType("int");

                    b.Property<string>("SqlCmdPassword")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("SqlCmdServer")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("SqlCmdUser")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("StudentDbConnection")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("SwaggerPath")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "SessionId" }, "IX_Exams_SessionId");

                    b.HasIndex(new[] { "SessionId", "Name" }, "UQ_Exams_Session_Name")
                        .IsUnique();

                    b.ToTable("Exams");
                });

            modelBuilder.Entity("Infrastructure.ExamSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("SemesterId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "SemesterId" }, "IX_ExamSessions_SemesterId");

                    b.HasIndex(new[] { "SemesterId", "Name" }, "UQ_ExamSessions_Semester_Name")
                        .IsUnique();

                    b.ToTable("ExamSessions");
                });

            modelBuilder.Entity("Infrastructure.GradingJob", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<DateTime?>("FinishedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastError")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("SubmissionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "SubmissionId" }, "IX_GradingJobs_SubmissionId");

                    b.ToTable("GradingJobs");
                });

            modelBuilder.Entity("Infrastructure.RunLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<string>("FilePath")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("JobId")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "JobId" }, "IX_RunLogs_JobId");

                    b.ToTable("RunLogs");
                });

            modelBuilder.Entity("Infrastructure.Semester", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Name" }, "UQ_Semesters_Name")
                        .IsUnique();

                    b.ToTable("Semesters");
                });

            modelBuilder.Entity("Infrastructure.Submission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ExamId")
                        .HasColumnType("int");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("LastError")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("StudentName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("SubmittedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<decimal>("TotalScore")
                        .HasColumnType("decimal(8, 2)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "ExamId" }, "IX_Submissions_ExamId");

                    b.HasIndex(new[] { "Status" }, "IX_Submissions_Status");

                    b.ToTable("Submissions");
                });

            modelBuilder.Entity("Infrastructure.TestCase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<int?>("DependencyTestCaseId")
                        .HasColumnType("int");

                    b.Property<int>("ExamId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PostmanItemId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("Score")
                        .HasColumnType("decimal(6, 2)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "DependencyTestCaseId" }, "IX_TestCases_DependencyTestCaseId");

                    b.HasIndex(new[] { "ExamId" }, "IX_TestCases_ExamId");

                    b.HasIndex(new[] { "ExamId", "Name" }, "UQ_TestCases_Exam_Name")
                        .IsUnique();

                    b.HasIndex(new[] { "ExamId", "PostmanItemId" }, "UQ_TestCases_Exam_PostmanItemId")
                        .IsUnique();

                    b.ToTable("TestCases");
                });

            modelBuilder.Entity("Infrastructure.TestResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<decimal>("EarnedScore")
                        .HasColumnType("decimal(8, 2)");

                    b.Property<bool>("IsPassed")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSkipped")
                        .HasColumnType("bit");

                    b.Property<string>("Log")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SubmissionId")
                        .HasColumnType("int");

                    b.Property<int>("TestCaseId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "SubmissionId" }, "IX_TestResults_SubmissionId");

                    b.HasIndex(new[] { "TestCaseId" }, "IX_TestResults_TestCaseId");

                    b.HasIndex(new[] { "SubmissionId", "TestCaseId" }, "UQ_TestResults_Submission_TestCase")
                        .IsUnique();

                    b.ToTable("TestResults");
                });

            modelBuilder.Entity("Infrastructure.Exam", b =>
                {
                    b.HasOne("Infrastructure.ExamSession", "Session")
                        .WithMany("Exams")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Exams_ExamSessions");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("Infrastructure.ExamSession", b =>
                {
                    b.HasOne("Infrastructure.Semester", "Semester")
                        .WithMany("ExamSessions")
                        .HasForeignKey("SemesterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ExamSessions_Semesters");

                    b.Navigation("Semester");
                });

            modelBuilder.Entity("Infrastructure.GradingJob", b =>
                {
                    b.HasOne("Infrastructure.Submission", "Submission")
                        .WithMany("GradingJobs")
                        .HasForeignKey("SubmissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_GradingJobs_Submissions");

                    b.Navigation("Submission");
                });

            modelBuilder.Entity("Infrastructure.RunLog", b =>
                {
                    b.HasOne("Infrastructure.GradingJob", "Job")
                        .WithMany("RunLogs")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_RunLogs_GradingJobs");

                    b.Navigation("Job");
                });

            modelBuilder.Entity("Infrastructure.Submission", b =>
                {
                    b.HasOne("Infrastructure.Exam", "Exam")
                        .WithMany("Submissions")
                        .HasForeignKey("ExamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Submissions_Exams");

                    b.Navigation("Exam");
                });

            modelBuilder.Entity("Infrastructure.TestCase", b =>
                {
                    b.HasOne("Infrastructure.TestCase", "DependencyTestCase")
                        .WithMany("InverseDependencyTestCase")
                        .HasForeignKey("DependencyTestCaseId")
                        .HasConstraintName("FK_TestCases_Dependency");

                    b.HasOne("Infrastructure.Exam", "Exam")
                        .WithMany("TestCases")
                        .HasForeignKey("ExamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_TestCases_Exams");

                    b.Navigation("DependencyTestCase");

                    b.Navigation("Exam");
                });

            modelBuilder.Entity("Infrastructure.TestResult", b =>
                {
                    b.HasOne("Infrastructure.Submission", "Submission")
                        .WithMany("TestResults")
                        .HasForeignKey("SubmissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_TestResults_Submissions");

                    b.HasOne("Infrastructure.TestCase", "TestCase")
                        .WithMany("TestResults")
                        .HasForeignKey("TestCaseId")
                        .IsRequired()
                        .HasConstraintName("FK_TestResults_TestCases");

                    b.Navigation("Submission");

                    b.Navigation("TestCase");
                });

            modelBuilder.Entity("Infrastructure.Exam", b =>
                {
                    b.Navigation("Submissions");

                    b.Navigation("TestCases");
                });

            modelBuilder.Entity("Infrastructure.ExamSession", b =>
                {
                    b.Navigation("Exams");
                });

            modelBuilder.Entity("Infrastructure.GradingJob", b =>
                {
                    b.Navigation("RunLogs");
                });

            modelBuilder.Entity("Infrastructure.Semester", b =>
                {
                    b.Navigation("ExamSessions");
                });

            modelBuilder.Entity("Infrastructure.Submission", b =>
                {
                    b.Navigation("GradingJobs");

                    b.Navigation("TestResults");
                });

            modelBuilder.Entity("Infrastructure.TestCase", b =>
                {
                    b.Navigation("InverseDependencyTestCase");

                    b.Navigation("TestResults");
                });
#pragma warning restore 612, 618
        }
    }
}
