/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { TestCaseDto } from '../../models/test-case-dto';

export interface ApiExamsExamIdTestcasesIdPatch$Plain$Params {
  examId: number;
  id: number;
      body?: {
'FilePath'?: string;
'File'?: Blob;
}
}

export function apiExamsExamIdTestcasesIdPatch$Plain(http: HttpClient, rootUrl: string, params: ApiExamsExamIdTestcasesIdPatch$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<TestCaseDto>> {
  const rb = new RequestBuilder(rootUrl, apiExamsExamIdTestcasesIdPatch$Plain.PATH, 'patch');
  if (params) {
    rb.path('examId', params.examId, {});
    rb.path('id', params.id, {});
    rb.body(params.body, 'multipart/form-data');
  }

  return http.request(
    rb.build({ responseType: 'text', accept: 'text/plain', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<TestCaseDto>;
    })
  );
}

apiExamsExamIdTestcasesIdPatch$Plain.PATH = '/api/exams/{examId}/testcases/{id}';
