/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { TestCaseDto } from '../../models/test-case-dto';

export interface ApiExamsExamIdTestcasesIdGet$Json$Params {
  examId: number;
  id: number;
}

export function apiExamsExamIdTestcasesIdGet$Json(http: HttpClient, rootUrl: string, params: ApiExamsExamIdTestcasesIdGet$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<TestCaseDto>> {
  const rb = new RequestBuilder(rootUrl, apiExamsExamIdTestcasesIdGet$Json.PATH, 'get');
  if (params) {
    rb.path('examId', params.examId, {});
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'text/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<TestCaseDto>;
    })
  );
}

apiExamsExamIdTestcasesIdGet$Json.PATH = '/api/exams/{examId}/testcases/{id}';
