/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ExamDto } from '../../models/exam-dto';

export interface ApiExamsExamIdGet$Json$Params {
  examId: number;
}

export function apiExamsExamIdGet$Json(http: HttpClient, rootUrl: string, params: ApiExamsExamIdGet$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<ExamDto>> {
  const rb = new RequestBuilder(rootUrl, apiExamsExamIdGet$Json.PATH, 'get');
  if (params) {
    rb.path('examId', params.examId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'text/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ExamDto>;
    })
  );
}

apiExamsExamIdGet$Json.PATH = '/api/exams/{examId}';
