/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ExamDtoPagedResult } from '../../models/exam-dto-paged-result';

export interface ApiExamsGet$Plain$Params {
  search?: string;
  sort?: string;
  order?: string;
  page?: number;
  pageSize?: number;
}

export function apiExamsGet$Plain(http: HttpClient, rootUrl: string, params?: ApiExamsGet$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<ExamDtoPagedResult>> {
  const rb = new RequestBuilder(rootUrl, apiExamsGet$Plain.PATH, 'get');
  if (params) {
    rb.query('search', params.search, {});
    rb.query('sort', params.sort, {});
    rb.query('order', params.order, {});
    rb.query('page', params.page, {});
    rb.query('pageSize', params.pageSize, {});
  }

  return http.request(
    rb.build({ responseType: 'text', accept: 'text/plain', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ExamDtoPagedResult>;
    })
  );
}

apiExamsGet$Plain.PATH = '/api/exams';
