/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface SubmissionDto {
  examId?: number;
  filePath?: string | null;
  id?: number;
  status?: number;
  studentCode?: string | null;
  studentName?: string | null;
}
