/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { SubmissionTestResultDto } from '../models/submission-test-result-dto';
export interface SubmissionReportDto {
  examId?: number;
  lastError?: string | null;
  reportPath?: string | null;
  results?: Array<SubmissionTestResultDto> | null;
  status?: string | null;
  studentCode?: string | null;
  studentName?: string | null;
  submissionId?: number;
  totalScore?: number;
}
